### ISSUE TITLE
all movement gone crazy!??

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#102]
everyone just moves around completely erratic!?? even after reloading saved game!  (on the bright side without game no longer calculating pathing it speeds up ;-) )

[0903 schorched wtf.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7952962/0903.schorched.wtf.zip)

**Comment by SerialKicked** [comment]
I guess that, yes, queuing over 7000 jobs in a gigantic map overflowing with people & mobs all that at 2.5 speed, yes it will do that. Physics skip so many steps to compensate for the other calculations that movements break down.

Deleting that gigantic building zone fixes the problem.

I'll see what I can do to get the game to run better under such extreme situations. Can't make any promise.

**Comment by IvanBajlo** [comment]
what 7000 jobs... oh wait that massive build floor on the ground level was made by accident when game went crazy and somehow sent my cursor to jump around (I think it was event with some fauna arriving on the map), also map isn't gigantic but standard for scorched scenario, yeah after removing that gigantic floor and reloading its back to normal...

**Comment by SerialKicked** [comment]
It's fine, thanks to that report, i found a bottleneck in the code

**Comment by SerialKicked** [comment]
Fixed
