### ISSUE TITLE
can we get different color when mushroom gets spores?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#103]
at the moment all giant mushroom have the same color making it difficult to pick those with spores so it would be nice to have them in different color for easy spotting 

BTW here another idea - very rare poisonous mushroom as alternative source of poison?

![image](https://user-images.githubusercontent.com/91120787/151425921-c0ebcacd-7026-4866-9ca8-3b120c60bcd8.png)

**Comment by SerialKicked** [comment]
Having spores or not depends on how grown they are, the older ones (largest) have spores. But yeah I will be adding more plant types in the future :)
