### ISSUE TITLE
sleepy guy? ;-)

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#104]
this guys spent very long time in bed... was he doing morning gymnastics? ;-)

![image](https://user-images.githubusercontent.com/91120787/151439181-b37d59b5-3ba4-4d04-a090-2fb5aa4ec78a.png)

**Comment by SerialKicked** [comment]
Mmmmh, weird. Probably a case I didn't account for when implementing the new version of "use furniture" job in the last patch. 

I'll have a look.

**Comment by SerialKicked** [comment]
I think it's fixed in patch i'm about to publish. I'll keep this one open until i can make sure.
