### ISSUE TITLE
fire blocks exit everyone dies... 👍 

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#109]
while it does happen in reality it can be real overkill in the game... fire can jump from settler to settler and settlers standing next to fire can catch fire as if they are kindle wood... this is probably causing massive problems when settlers automatically attempt to put down each fire they spot as they get burns very quickly 

so I propose this:

1. drastically lower chance for living creatures to catch fire from the tile next to them just by standing next it 

2. (more complicated probably post 1.0) if settlers goes through fire besides burns there is chance that piece of their clothing catches fire and gets destroyed instead of settlers just bursting into flames

![image](https://user-images.githubusercontent.com/91120787/153689291-a8d37b23-cec8-4089-b6b5-4660e3ec56a3.png)

**Comment by SerialKicked** [comment]
Tile determine if they can burn or not based on having at least one thing that can burn placed there, no matter if it's a settler a furniture or a wooden wall. It's going to spread based on the fire density (which grows as long as there's fuel).

As such fire doesn't spread from settler to settler but from tile to tile. The fact it's a settler ain't relevant to the fire as much as it's concerned. Could be beds, or chairs.

As explained the last time i closed a similar item, it's not going to change. This system works and it's extremely CPU efficient, I'm definitely not going to add special cases for peons/mobs as it would kill performance or make me redesign the whole thing from scratch.

Best thing I can do is to add a better detection for settlers to "extinguish fire on themselves" whenever possible.
