### ISSUE TITLE
Presets for job and cattle manager

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#11]
I know its on TO DO list already but it never hurts to add it to few more TO DO lists ;-)

**Comment by SerialKicked** [comment]
It's already in the 0.8.6 "Done" list :)
(only apply to new games, because the game can't guess if you haven't set anything on purpose or not)

**Comment by IvanBajlo** [comment]
> It's already in the 0.8.6 "Done" list :) (only apply to new games, because the game can't guess if you haven't set anything on purpose or not)

are you sure we are talking about the same thing because I don't see it anywhere?

**Comment by IvanBajlo** [comment]
I see now cattle has been fixed but we still have jobs which are pain in the a*** to set up each time...

**Comment by SerialKicked** [comment]
jobs are setup properly. each animal species gets the first job for that species, set on repeat forever, by default.
![yQZhuTEXCf](https://user-images.githubusercontent.com/1781563/135736183-b84043e0-5b61-49c3-aaaf-c427de6cad7c.png)
