### ISSUE TITLE
still getting mutant cannibals

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#115]
few mutants still get that trait from time to time... also mutants should probably get different text regarding profession "used to be a mutant" ;-)

![image](https://user-images.githubusercontent.com/91120787/153733994-0797392c-1ef0-47ed-86b9-d9a77b84c532.png)

**Comment by SerialKicked** [comment]
I can't "un mutant" their profession. It works like that. 

But yes about cannibal being a duplicate, not sure why it's happening

**Comment by IvanBajlo** [comment]
I'm no English major but it should probably say something like "She/he is a mutant" not "used to be" ;-)

**Comment by SerialKicked** [comment]
that's a side effect of having procedurally generated text. I'll need to look at this. And i probably won't fix it anytime soon, because it'll be too much of a hassle.
