### ISSUE TITLE
enhancement: center on event location

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#116]
if players disables center camera on special event in settings (because its annoying for camera to jump while doing something else) there is no option to center on the event location (fire event double click at lest jump to fire location)

![image](https://user-images.githubusercontent.com/91120787/153734288-4209a43b-59ba-4ce8-bd66-941e238423c0.png)

**Comment by SerialKicked** [comment]
Reeeeeeee
