### ISSUE TITLE
Disable option for grow lamp

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#12]
Moving them outside of power range looks like silly solution (which probably doesn't work for coal powered ones... I would need to  lock does in a room)

**Comment by SerialKicked** [comment]
Yeah, an on/off switch makes sense. Wish will be granted! :D

**Comment by SerialKicked** [comment]
![Collapse_GJJWPOIyRf](https://user-images.githubusercontent.com/1781563/135835741-3b7e7774-64cf-41b1-aa38-720f93c6fed3.png)

It's there already, lol. Well, i added one for normal lamps too.

**Comment by IvanBajlo** [comment]
when game dev doesn't know he has two grow lamps :D

![image](https://user-images.githubusercontent.com/91120787/135838171-3f2dcef4-e457-4479-83ba-557d994ab5bf.png)

**Comment by SerialKicked** [comment]
:'( lol anyway, fixed :)
