### ISSUE TITLE
everyone wants private room?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#121]
but I can find only one settler with 1000 skill but somehow all are experienced?

[0910 pandemonium.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/8181819/0910.pandemonium.zip)

![image](https://user-images.githubusercontent.com/91120787/156669828-6d5e5e4a-a4cd-40e6-82a2-1ed5e02219ce.png)

**Comment by SerialKicked** [comment]
I'll check but experience isn't tied to skill proficiency. It's just tied to how many jobs they complete and how many things they killed. The fact it used to roughly align with skill going to 1k was just coincidental.

**Comment by SerialKicked** [comment]
Yep, checked. 

Two in-game months is roughly when people start to require private bedrooms normally (especially underground where you have to do a lot of digging to make room). Working as usual afaik.

**Comment by IvanBajlo** [comment]
I guess previously everyone got to 1000 quickly and I somehow thought it was connected.
