### ISSUE TITLE
exotic pet trader has no eggs for sale!

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#122]
![image](https://user-images.githubusercontent.com/91120787/156783532-c6bcdac3-e906-4aeb-bd9a-7daf9a05ddf4.png)

**Comment by IvanBajlo** [comment]
[0910 pandemonium.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/8186646/0910.pandemonium.zip)

**Comment by SerialKicked** [comment]
Uh. Strange. I might (well i definitely did, given the screenshot) have overlooked something about egg traders.
