### ISSUE TITLE
unlimited garage?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#123]
wasn't there a check that prevented building more then allowed? it seems to broken now and one can build as many as one wants (of course once max number is built no extra can be built)

I did wait to start building until I researched almost everything but logistics so I should have been able to build only 3

![image](https://user-images.githubusercontent.com/91120787/156794899-de21efe7-0f65-4dbf-91a4-af48aa039efa.png)

**Comment by SerialKicked** [comment]
Nice find. The check must have broke when I merged/simplified the way player building placement/copy was done.
I'll get that fixed before release
