### ISSUE TITLE
stuck at 13 settlers?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#124]
started with 12 in bunker (plague scenario) I had two events with new settlers (3 + 2), 4 got killed since base was swarming with fauna but after that no new events with settlers? WAD or bug?

[0910 pandemonium.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/8188747/0910.pandemonium.zip)

**Comment by SerialKicked** [comment]
random event gonna random event.
I'll double check tomorrow, though.

**Comment by SerialKicked** [comment]
Recruit event is in the list of possible events, you've been unlucky. Technically i probably should find a way to make them appear on a more predictable fashion, but in the meantime, ain't a bug.
