### ISSUE TITLE
can't recruit in combat mode?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#126]
once combat mode is on military skill gets grayed out and it no longer possible to force recruit individual settler or turn on military skill? 

this makes thing problematic if you want to move "civilian" out of harms way or send more troops into combat

![image](https://user-images.githubusercontent.com/91120787/182016183-f9502fa7-0af6-4b76-8505-a66a97355658.png)

**Comment by SerialKicked** [comment]
Intended change. If a POI is under siege, it's too late to evacuate or recruit. The system need a "before siege" warning, agreed, tho
