### ISSUE TITLE
expedition loot stays on the floor

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#127]
even after loading save game it stays there: [1_0 beta.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/9228548/1_0.beta.zip)

![image](https://user-images.githubusercontent.com/91120787/182019123-ce50abbd-b003-4c22-94df-63606c332984.png)

**Comment by IvanBajlo** [comment]
other loot seems to be left behind at random?

![image](https://user-images.githubusercontent.com/91120787/182020794-5a342122-7041-44e2-8cf9-2754405f6fe8.png)

**Comment by IvanBajlo** [comment]
![image](https://user-images.githubusercontent.com/91120787/182020831-3f90c728-32a8-4b6e-bf0a-e66a1fbfe81f.png)

**Comment by IvanBajlo** [comment]
only after expedition returned from the second run did they finally started to collect items

**Comment by IvanBajlo** [comment]
it seems to be storage issue? but there is suppose to be enough storage for certain item types (like food and rifles)?

**Comment by IvanBajlo** [comment]
![image](https://user-images.githubusercontent.com/91120787/182021267-d934f4bd-f76c-410d-9590-680e94cd4d5a.png)

**Comment by IvanBajlo** [comment]
my guess would be there is too much loot and since certain loot items can't fit into storage nothing is moving? in that case a warning should pop-up for the player to build more storage... or maybe make garage a storage but you can't launch new expedition until it has been emptied?

**Comment by SerialKicked** [comment]
Fixed in 1.0
