### ISSUE TITLE
story map is a bit small

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#128]
base map could use a sort of a "buffer zone" around it since enemy spawns and is almost immediately inside the base, newbie players might get overwhelmed easily... 

world map is also a bit barren with almost all locations protected with high level mobs, maybe few easy locations near player base with very low loot levels? just to add more life to it... maybe event triggered once expeditions become available, sort of "scouts report small looting location which will get picked clean in X days..."

**Comment by SerialKicked** [comment]
Depends on which act. Act 1 has very weak factions (assuming you don't go after the friendly militia), with just crossbows and stuff, their pets are the main issue. I've edited the map slightly to reduce the mob count overall, slowed down expansion speed and added a few "not owned by a main faction" locations to compensate. 

Act 2+ are meant to be difficult.
