### ISSUE TITLE
Save game menu takes 20 seconds to open?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#13]
![image](https://user-images.githubusercontent.com/91120787/135720297-81f17fbb-2549-4582-95af-66a61b4c9a5a.png)

![image](https://user-images.githubusercontent.com/91120787/135720348-71fc97be-cbb7-41ca-98c6-19559f4d6bec.png)

**Comment by IvanBajlo** [comment]
it speeds up after opening few times...

**Comment by SerialKicked** [comment]
It can take a little while for the game to retrieve save information, especially if you have many saves. It gets faster because your computer is basically "caching" the results. 

I'll see what I can do, but probably won't be much.
