### ISSUE TITLE
Automatic crafting recategorization

### ISSUE THREAD

**Issue by FulcrumA** [AnarkisGaming/ATC-Feedback#134]
**Posting here an entry from Discord, as requested:**

> A small QoL change - if in crafting menu someone specifies the number of items to be crafted, the category automatically would change from "Forever" to "Do it X times". A few clicks and dropdown menus opening when someone manages multiple crafting stations really adds up.

**Comment by SerialKicked** [comment]
I'm not sure I understand the request. 

No one tells you to build anything, outside of very specific story mode quests and I guess during the tutorial, but that's sorta the point of the tutorial? If you meant the player, the field is read-only outside of "Do X times" mode and I'm not gonna make this field writeable in the 2 modes where its content is meaningless. 

You don't need to click on any of those drop down menus and quantity fields. Just use your mouse wheel to change their respective values. (for the quantity one, you can also shift-m.wheel to change values by higher increments). It's a lot easier and saves, well, infinity clicks :)

**Comment by FulcrumA** [comment]
I thought that the category automatically changing from default "forever" to "do x times" when the player attempts to alter quantity would be a nifty, small accessibility change. Anyway, thanks for the hints, I'll take a closer look.
