### ISSUE TITLE
Presetting defensive positons on map

### ISSUE THREAD

**Issue by FulcrumA** [AnarkisGaming/ATC-Feedback#135]
**Posting here an entry from Discord, as requested:**

> Would be nice to be able to set up defensive positions before time for melee/ranged (and having ammo), or per character, to take, as a counterpart to fleeing to safe zone order for non-military.

**Comment by IvanBajlo** [comment]
IIRC that one is already in the game as patrol zone, not sure if it is part of the tutorial

![image](https://user-images.githubusercontent.com/91120787/192249054-734dc5bd-5b4d-4ce6-8956-ebda377e0b08.png)

![image](https://user-images.githubusercontent.com/91120787/192249090-c52015c5-f963-4fb4-8036-9fe76d07d2f1.png)

**Comment by FulcrumA** [comment]
Not mentioned in the tutorial but yes, in some way current features allow that. Closing.
