### ISSUE TITLE
Single lamp not working?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#14]
even after reloading game lamp in dining room doesn't give light... all other lamps work normally and all were generated at the start...

![image](https://user-images.githubusercontent.com/91120787/135720655-c3b072fb-843b-49b5-8414-0e05b5b3f817.png)

**Comment by IvanBajlo** [comment]
save game

[0860 vault.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7271622/0860.vault.zip)

**Comment by SerialKicked** [comment]
uh, i'll have a look. It's probably just a "broken" procedural lamp that i used by mistake in the vault building.
Fixed.

**Comment by IvanBajlo** [comment]
it seems that lamp in the bathroom is set as clutter?

![image](https://user-images.githubusercontent.com/91120787/136701855-8b03a8f8-a2af-4a25-93f6-26429f8f09cd.png)
