### ISSUE TITLE
Selection in pop menu unreliable

### ISSUE THREAD

**Issue by SerialKicked** [AnarkisGaming/ATC-Feedback#144]
Especially visible when using the control [g]roup shortcut from the pop menu directly, clicked survivor is not always properly selected. And the double click is occasionally unreliable.

**Comment by StStep** [comment]
I was having this problem and I think it happens when clicking on the characters names in the menu rather than the background menu box for the characters. I've started intentionally avoiding clicking names when selecting people and that's helped me a bit.

**Comment by SerialKicked** [comment]
Yeah, it's partly that. Also some areas are sorta unclickable because they have their own function, like toggle on/off a skill. And when the menu was draggable, the drag function would occasionally "intercept" the click.

This is mostly fixed.
