### ISSUE TITLE
Moving out & Expeditions

### ISSUE THREAD

**Issue by SerialKicked** [AnarkisGaming/ATC-Feedback#146]
People who are in an expedition should probably be counted in when trying to move the base elsewhere. There won't be changes to the prod-center workers, though, as it's not a given that you want to bring them with you (especially if moving within the same map).

**Comment by IvanBajlo** [comment]
can we get cool looking road train/caravan from Mad Max 2 in 2.0. ;-)

and road battle minigame featuring tanker truck :D 

https://youtu.be/c63AgdDyyO8?t=234

**Comment by SerialKicked** [comment]
Sure thing :D
