### ISSUE TITLE
Trader probably shouldn't pop up while base still hasn't been revealed

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#15]
![image](https://user-images.githubusercontent.com/91120787/135722386-6baf1776-5922-4229-9fef-31f32e02ab46.png)

**Comment by SerialKicked** [comment]
Oh right, this one. They are normally unlocked at radio tech (independently of base revealed, given, it's a radio communication, after all). But this one is unlocked after animal care because of the eggs. Erf, i could lock this one behind base revealed, but meh.

**Comment by IvanBajlo** [comment]
this one should also probably be locked ;-)

![image](https://user-images.githubusercontent.com/91120787/135723866-6e82514f-6495-4ab8-b018-5da2f0201ed0.png)

**Comment by SerialKicked** [comment]
Not really, animal moving in the base's location aren't stopped by the hidden tag. It's intended. 
I might have to find a way to limit overpopulation, though.
