### ISSUE TITLE
Floors can be laid multiple times in the same space

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#16]
one can order floor build and then again over the same space multiple times... and if you change floor type all floor switch build orders beneath that change to last floor type... didn't test what happens if I let them build but still no point in having pointless jobs being added to work order...

![image](https://user-images.githubusercontent.com/91120787/135722509-611862a3-f80f-4794-aca0-64cc12f77731.png)

**Comment by SerialKicked** [comment]
uh, interesting. No idea how i could have let that one slip. Will fix in 086

**Comment by SerialKicked** [comment]
Resolved.
