### ISSUE TITLE
Base revealed despite still being underground?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#17]
I got recruits events thinking I was still hidden... btw **recruit all** button could be useful...

![image](https://user-images.githubusercontent.com/91120787/135725100-a3f49860-8805-41ca-b745-e61d1c5b2db8.png)

did my stairs to level 3 cause this? also some kind of a warning that base has been revealed might be nice ;-)

**Comment by SerialKicked** [comment]
I thought i fixed the stair thing. Welp, one more to the list. Good job!
And, yes, a warning would indeed be nice

**Comment by IvanBajlo** [comment]
unfortunately no save game before being revealed...

[0860 revealed.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7271835/0860.revealed.zip)

**Comment by SerialKicked** [comment]
Fixed. Loading a savegame was resetting surface access.
