### ISSUE TITLE
enemies teleport below despite stairs removed!?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#20]
I've removed stairs and let tribal fight with crazed robots but some of them still manage to teleport below

![image](https://user-images.githubusercontent.com/91120787/136076939-8f40eba8-e391-4311-b5cd-856e0522f660.png)

**Comment by IvanBajlo** [comment]
save game with teleported tribal
[0860 teleport.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7288149/0860.teleport.zip)

save game just before attack... now random attack spawns each time
[0860 before attack.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7288165/0860.before.attack.zip)

**Comment by SerialKicked** [comment]
Ohhh nice, finally some useable data about that layer teleport thing.
Thanks

I assume the stair was in that small 3x3 room.

**Comment by SerialKicked** [comment]
I think i know what's up. Once a path is set, movement does check for new walls or closed doors, but i don't think i made a similar check for stairs. So if a stair gets deleted while the enemy was *already* pathing, it'll just ignore the deletion. At least that's my assumption.

**Comment by IvanBajlo** [comment]
yep I like to isolate stairs in small rooms just in case ;-)
