### ISSUE TITLE
mines are deadly!

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#27]
which is good BUT I got 2 people killed to mines already... can we get option to make a long detour which results in expedition not doing anything for a day (maybe even two?)?

![image](https://user-images.githubusercontent.com/91120787/136711749-8cbf75ea-59db-4f27-a743-98fe81ca7a0d.png)

**Comment by SerialKicked** [comment]
That's probably an option i could had, having one of the choices forcing the expedition to "pause" for a set amount of time. If it was just for the mines, it's just say no, but it's something i could use for future events.

That's not very high priority, but will do.
