### ISSUE TITLE
apple tree seedling not visible unless cursor is right on top of it

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#28]
![image](https://user-images.githubusercontent.com/91120787/136712913-f4b331b8-a3c8-4167-a892-721750fb6f1a.png)

![image](https://user-images.githubusercontent.com/91120787/136712925-14d7a2da-35e9-4f86-95f2-565c1b1fc01b.png)

**Comment by SerialKicked** [comment]
lol and they block light but shouldn't. 

I'll get that sorted out.
