### ISSUE TITLE
job error I've reported on discord

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#29]
but lets have it here also just for fun and get my numbers up ;-)

![image](https://user-images.githubusercontent.com/91120787/136712955-a7f6a749-9998-491f-9b72-2a13fbc4cf41.png)

**Comment by IvanBajlo** [comment]
ah yes no haulers are coming for water which is stuck in limbo despite it being connected to empty storage

![image](https://user-images.githubusercontent.com/91120787/136714376-b72a5254-4cd3-43e2-8602-a3c49759b3fd.png)

**Comment by IvanBajlo** [comment]
related save game
[0860 not working.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7318438/0860.not.working.zip)

**Comment by SerialKicked** [comment]
Fixed, probably, i think. :D
