### ISSUE TITLE
debris table can be used

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#31]
same as that bug with beds, settlers in dinning room make no difference between debris and built items

![image](https://user-images.githubusercontent.com/91120787/137589600-c72e130f-1ee9-4192-bef4-afa6672b4e95.png)

**Comment by IvanBajlo** [comment]
wasn't the bed bug fixed?

![image](https://user-images.githubusercontent.com/91120787/137590829-8fbda073-c17e-49f0-8244-2ecae3bfb868.png)

**Comment by SerialKicked** [comment]
Did you spawn in that bunker?

If not, i'll have a look. I might need the save, tho.

**Comment by SerialKicked** [comment]
Fixed. Changes will only apply to new saves after the update.
