### ISSUE TITLE
tomato seeds description cut short

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#32]
![image](https://user-images.githubusercontent.com/91120787/137591271-f7cdf4e7-999f-48ba-af14-5c31edaac4cd.png)

**Comment by SerialKicked** [comment]
All descriptions in that menu are 2 liners. Having it "overflow" looks a lot worse. Right click for full description. I'll get rid off the cut 3rd line, tho.

**Comment by SerialKicked** [comment]
Menu altered so the text is at least not left with "half a line". Added tooltip with full text.
