### ISSUE TITLE
when depressed scavenging gets disabled for settlers but it seems to stay disabled afterwards!?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#35]
![image](https://user-images.githubusercontent.com/91120787/137592331-d757d2a2-3642-4b93-b62e-e75eb2485813.png)

![image](https://user-images.githubusercontent.com/91120787/137592278-6cff39d7-a4ba-4e9b-bd38-0ec27799ea84.png)

**Comment by SerialKicked** [comment]
Uh, I was certain i took care of that like 200 versions ago. Some code must have interfered. I'll get that sorted out.
