### ISSUE TITLE
dissasembling can get settlers stuck!

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#36]
apparently since disassembling still works diagonally this can result in settlers getting stuck since it seem they can teleport to the location of the disassembled items!?

![image](https://user-images.githubusercontent.com/91120787/137595408-e7d6d420-bb8c-4c59-af8d-e59c583156de.png)

**Comment by SerialKicked** [comment]
There was  door there i'd guess. doors don't know how to stay open when a settler is on their tile and have a bad habit of "pushing" them  if they stay too long. They probably don't care about diagonals. hence this result.

Might be fixable.

**Comment by IvanBajlo** [comment]
there might have been some object in that corner but I don't have early save... at start I usually order them to dissemble low value items (chairs, table, doors, windows...) first to gain experience and then more valuable objects when I already have exp to gain maximum salvage

**Comment by SerialKicked** [comment]
#45 to centralize "my settler teleported somewhere else" issues.
