### ISSUE TITLE
hostile vault stuck against enemies?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#37]
if we have hostile vault on the map it seems people there can get stuck on objects and don't fight back!?

![image](https://user-images.githubusercontent.com/91120787/137595638-411f98cf-393b-4af0-9cfe-2db39450cc64.png)

**Comment by IvanBajlo** [comment]
and a lot of bugs like to hang in front of their doors ;-)

![image](https://user-images.githubusercontent.com/91120787/137595703-a6a9bd96-aea2-4ca7-9404-30c86e651fc6.png)

**Comment by IvanBajlo** [comment]
also I can't select persons which are stuck on top of furniture

**Comment by SerialKicked** [comment]
Oh, yeah, didn't think of that, FaunaAI will get stuck on doors with the attack job changes. Shit. I'll patch that out, probably quickly because it's ugly.

The rest, i'm not sure what's up, I'll have a look

**Comment by IvanBajlo** [comment]
ai remains stuck on a lamp and not defending itself even after loading savegame so here you go and enjoy the weekend ;-)

[0862 ai stuck.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7357910/0862.ai.stuck.zip)

**Comment by IvanBajlo** [comment]
this gal isn't stuck on anything but still isn't shooting it seems they only seem me as hostile not the fauna

![image](https://user-images.githubusercontent.com/91120787/137596217-97da777c-d877-44df-a5dc-98467300ceb8.png)

![image](https://user-images.githubusercontent.com/91120787/137596238-d34b35f1-968a-4444-b770-8dcf485d9f96.png)

**Comment by SerialKicked** [comment]
Yeah, i think the vault people still think they are "hidden" and in ambush stance, waiting for you to enter the room, it's not accounting for a 3rd party hostile starting to nibble on them. Shouldn't be too much of a problem to fix.
