### ISSUE TITLE
recruitment ends if player clicks anywhere on the city map!

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#40]
if recruitment window pops up on the city map, clicking anywhere on the map (outside recruitment window) ends recruitment

![image](https://user-images.githubusercontent.com/91120787/137598211-c73305f9-5ff1-4130-9183-17940d1ecb62.png)

**Comment by IvanBajlo** [comment]
two groups or recruits arrive in a few hours... if player recruits first group then game properly locks the UI and second group cannot fail but if player clicks anywhere on the map with the first then the second can also fail

[0862 recruitment bug.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7358052/0862.recruitment.bug.zip)

**Comment by SerialKicked** [comment]
Yeah, that's the reason why the map was initially pausing the game, not all menus are fond of that mode. Ofc, now we can't force the map to pause the game, because expeditions, so it's still a bit of a mess.

Nice find, though. I'll get it fixed.

**Comment by SerialKicked** [comment]
Fixed in house
