### ISSUE TITLE
faction respawns

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#41]
and after second destruction second base icon stays on the map!

![image](https://user-images.githubusercontent.com/91120787/137601331-ab4558f6-aea2-4d28-b22c-79daba649599.png)

game with respawned Neo Roma before its destruction

[0862 faction respawn bug.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7358234/0862.faction.respawn.bug.zip)

after destruction for the second time

[0862 neo roma.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7358236/0862.neo.roma.zip)

**Comment by SerialKicked** [comment]
I hate you very much :D

**Comment by SerialKicked** [comment]
oops, the second neo roma didn't respawn, it was always there :D 

That's a perma hostile neo roma faction for the new scenario. It wasn't supposed to show up here. I'll get it to go back into its hidey hole
