### ISSUE TITLE
both exit buttons stopped working! :-o

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#42]
- so I loaded my autosave before destroying Neo Roma for the second time
- made a separate savegame (0862 faction respawn bug) which can be downloaded in another issue but here also
- then went to Neo Roma to test if diplomacy still works and it did although no gifts were possible
- then decided to exit the game because my PC was getting really sluggish (got tons of Chrome windows opened) and then realized I couldn't! neither to main menu nor out of the game!

- loaded save again... and I can exit... do diplomacy with Neo Roma and they no longer work! bug confirmed... 

[0862 faction respawn bug.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7358240/0862.faction.respawn.bug.zip)

**Comment by SerialKicked** [comment]
lol omg

Ok, i know there's a bug in the world map. I've not found the why and how, but sometimes, if you manage to open the pause/main menu from the world map (and you shouldn't be allowed to, ESC is supposed to get you back to the base, that's the bug), then the exit buttons don't work.
