### ISSUE TITLE
when loading save leaving trader sometimes gets confused and goes back

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#43]
once he reaches trader zone he gets deleted and vanishes, WAD or bug?

![image](https://user-images.githubusercontent.com/91120787/137641253-1209df11-3c2d-4b98-b6cd-e07087caf4fe.png)

**Comment by IvanBajlo** [comment]
save game in question, out of 4 times I loaded the game, one time trader left normally but other 3 he turned back to trading area

[0862 neo roma.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7360663/0862.neo.roma.zip)

**Comment by SerialKicked** [comment]
It's a fail-safe in the TraderAI, which will make it blink out of existence if i's supposed to be time to leave the map, but couldn't or wasted too much time trying to. 

Generally happens after loading a save where the trader was already leaving. The "exit" point is recalculated too, so it might have to go back on its path, and the AI might get bored and teleport out instead.

I could "fix" it, but that's incredibly low priority, and it's a safety i'm not really willing to remove presently.

**Comment by SerialKicked** [comment]
Fixed
