### ISSUE TITLE
recruitment bug also happens if you click on random settler!?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#46]
same save file as before if I can click on random settler in the base recruitment can also fail, sometimes it works as it should but sometimes clicking on settlers removes recruitment window... :-(

BTW can we have auto-recruit everyone option since I usually don't care who I get, the more bodies the better ;-)

![image](https://user-images.githubusercontent.com/91120787/137645929-a03f178c-fe50-45f3-9b3e-4a554c97e94b.png)

**Comment by SerialKicked** [comment]
Same fix #40
