### ISSUE TITLE
laws not applying to all settlers equally!?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#47]
![image](https://user-images.githubusercontent.com/91120787/137646517-0130101b-0f58-4d8b-a2ba-ded099425036.png)

![image](https://user-images.githubusercontent.com/91120787/137646573-bdc9b566-89b6-44cd-86fd-813ac898101b.png)

**Comment by SerialKicked** [comment]
Uh, weird. It might take a minute or two for laws to apply to newcomers, but doesn't seem to be the case here. I'll have a look.

**Comment by SerialKicked** [comment]
~~Ok, seems that the code to apply that stuff to new arrivals got removed at some point during another change. I'll get it fixed.~~

edit: Not sure wtf happens here
