### ISSUE TITLE
firefighting zones?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#50]
- designed to cover certain area of woods/trees
- preferably walled off (not by wooden walls) to prevent fires from outside the zone spreading in
- dead trees and dry grass (which should have higher chance to start a fire and spread it more rapidly) are automatically cleared by the settlers which in turn should lower chance of fire and fire spreads much slower

**Comment by SerialKicked** [comment]
Duplicate #61
