### ISSUE TITLE
water plants catching fire

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#51]
btw can fire jump across the wall?

![image](https://user-images.githubusercontent.com/91120787/138048342-6c1a4419-b116-40c7-83fc-19db58ce6148.png)

**Comment by IvanBajlo** [comment]
neverminded, yes fire can jump across walls, which makes walls useless as a way of halting fires from spreading

![image](https://user-images.githubusercontent.com/91120787/138048661-e4a18b9b-33b7-4fe1-b52f-8f1c97507608.png)

**Comment by SerialKicked** [comment]
add proper foundations that won't burn to your wall ;)

Also, this is for debugging and feature request, not general commentary

**Comment by IvanBajlo** [comment]
so water plants catching fire isn't a bug and walls should be built on floors??? yeah that makes perfect sense :-p

**Comment by SerialKicked** [comment]
Fire formula is not going to check for water below fuel source each single time an individual fire tile needs that info for performances reasons. Not gonna waste CPU cycles over such an inconsequential side effect. 

Walls should be built on proper **foundations**, not "floors". But that, that's a behavior I might change, even if it makes fire a lot less interesting behavior wise.

**Comment by IvanBajlo** [comment]
ok, so what the heck are **foundations**??? this is the first time I have ever heard that term! at lest in this game... the only other game that I know of required **foundations** to build on water...

**Comment by SerialKicked** [comment]
The tile the wall is built upon is its foundation. 

Don't bother anyway, I changed the feature given how confusing it seems to sounds. Fire proof walls will no longer let fire pass (except if it's a fence, like the metal fence, or well the wooden fence, but this one goes without saying).
