### ISSUE TITLE
camp fire preferred while water purifier gets ignored

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#52]
unless I put water purifier on high priority they are ignored most of the time and camp fire is preferred method of boiling water!?

![image](https://user-images.githubusercontent.com/91120787/138057025-25005716-1c17-44fb-bab6-189478e554fd.png)

**Comment by IvanBajlo** [comment]
save game

[0862 purifer.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7379491/0862.purifer.zip)

**Comment by SerialKicked** [comment]
You have 2076 jobs queued in that save, even with 81 people don't expect a low priority hauling job (bring stuff to water purifier) to get done for a looooong while, while a high priority cooking job (boil water) will be.  

Use your general priority menu and put hauling in your priority list, use a dedicated hauler, or keep the purifiers on high priority.

Game is working as expected under the conditions.

**Comment by IvanBajlo** [comment]
so water purifier is hauling job since it has no cooking involved while camp fire is cooking job since it is boiling water... got it... why on earth was I thinking that they would be in the same category... I'm sure nobody else will get confused ;-)

**Comment by SerialKicked** [comment]
The skill used is written at the top of that menu in your screenshot.

The idea is that the camp fire one is cooking because the guy will stay to "cook" the water (more or less efficiently), the other is an automated process where the items are just brought to the location by a random worker whose skill is not really relevant to the action.

**Comment by IvanBajlo** [comment]
there is skill listed!??? how come I never saw that before!??? this game has so much stuff to read that it will get categorized as visual novel ;-)
