### ISSUE TITLE
settlers going to the corner of the map looking for animals?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#53]
now this has to be some sort of bug ;-)

![image](https://user-images.githubusercontent.com/91120787/138132761-0d76e0ad-946f-4c7d-9015-9495945b491f.png)

**Comment by SerialKicked** [comment]
Definitely a bug. Going to (0,0) is a tell tale sign of a settler saying "I failed at finding the thing i'm looking for, I got a "null" as a response somewhere which translate to (0,0), and I couldn't detect it was the case before pathing there like an idiot"

Save would be nice if repeatable.

**Comment by IvanBajlo** [comment]
after saving and loading they reset and go back to normal... at lest for now... I'll keep my eye if it happens again

during bug
[0862 roster bug.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7382885/0862.roster.bug.zip)

before bug
[0862 base.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7382887/0862.base.zip)

**Comment by IvanBajlo** [comment]
minimap shows animals way to the right outside of walls, could this cause the bug?

![image](https://user-images.githubusercontent.com/91120787/138558803-054b50e8-069d-4d85-a766-adf196e83e3e.png)

**Comment by SerialKicked** [comment]
Nah, the placement of agents on the minimap is just not accurate (which is technically another bug :D), that doesn't impact gameplay or pathing.

**Comment by IvanBajlo** [comment]
yep here they go again...

[0863 map corner bug.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7403305/0863.map.corner.bug.zip)

![image](https://user-images.githubusercontent.com/91120787/138563665-7fdf3427-7df3-497e-88af-01ba2d929768.png)

**Comment by IvanBajlo** [comment]
![image](https://user-images.githubusercontent.com/91120787/138564683-018b1358-3384-4509-9e25-467f72134264.png)

**Comment by SerialKicked** [comment]
Yep, i see. You don't have to report each instance, I _will_ get that sorted out whenever i can :)

**Comment by IvanBajlo** [comment]
just getting my post count ;-)

here a mushroom growth blocked the path back :D

![image](https://user-images.githubusercontent.com/91120787/138565017-d9333556-d129-4540-98da-3737c34ec733.png)

**Comment by SerialKicked** [comment]
Getting your post count up is nice & all but I get email notifications for each post you make so I'd rather keep things limited to new/relevant information/bug/report/data in general. 

It's not a chatroom and we already have the discord channel for chatting :)

**Comment by IvanBajlo** [comment]
yep I've disabled email notifications since there was way to many of them :D

**Comment by SerialKicked** [comment]
Identified, fixed. next patch.
