### ISSUE TITLE
idea for guard posts and combat groups

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#54]
so here is simple solution to make base combat a bit easier...

temporary guard post: 
- simple zone to which 1-4 settlers can be assigned (once assigned they can no longer do expeditions and vice versa)
- each guard post is its own combat group which can be selected with CTRL+1-9 making them easy to select and move around as needed and will auto-return if left with orders for a few minutes (unless auto-return is turned off)
- settlers automatically shot at anyone who comes near the zone (or melee attack anyone in the zone) BUT don't leave the zone (and run all over the map like crazy)... this makes it simple to create kill box with ranged weapons on both sides (behind defense like barbed wire) and melee fighters at the bottleneck
- different settings depending on the situation:
1. mobilize when combat mode is on - settlers will man guard post only when combat mode is on
2. always manned, there will always be at lest one settlers at the post (while others eat or sleep), if combat starts others join in
3. no step back, in case of emergency settlers will stay at their posts no matter what

permanent guard post:
- same as above but its a building now, cannot be simply deleted or moved, for late game when base is mostly built
- comes with sandbags (requires material) upgrade with barbed fire and finally concrete bunker, MG etc.

**Comment by SerialKicked** [comment]
Guard posts are already on my to-do list, but you wrote a good break down of how they should work. nice.
