### ISSUE TITLE
do animals eat plants?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#57]
because my pasture is slowly getting barren?

![image](https://user-images.githubusercontent.com/91120787/138559629-7c814ed6-96a9-47ea-b29d-fd141fe511b4.png)

**Comment by SerialKicked** [comment]
Yeah, plants don't grow on zones , it was to avoid grass & tress fucking with the farms. But i guess it does the same on pastures, which i can explain away with animals eating the plants :D but repair zones... that's going to be harder to explain away :D. I'll tweak it.
