### ISSUE TITLE
Elusive raze job crash intercepted

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#58]
2021-10-23 20:51:35,236 [14] ERROR AG.GameProject.ATC.Program - Elusive raze job crash intercepted
System.NullReferenceException: Object reference not set to an instance of an object.
   at AG.GameProject.ATC.Jobs.RazeJob.DoJob(AGContainer pJobRunner)
   at AG.GameProject.ATC.Jobs.RazeJob.ExecuteJob(AGContainer pJobRunner)
   
   
![image](https://user-images.githubusercontent.com/91120787/138568233-beff3951-847b-450c-9339-963e778c6f5a.png)

**Comment by SerialKicked** [comment]
Anti crash system activated and worked, that's why you don't find crashes anymore :D

If you know what it was you were building and were and why and have a save, great. Otherwise, welp, you know as much as i do.

**Comment by IvanBajlo** [comment]
I think I was razing something in the sewers.. but can't repeat it :-(

[0863 raze bug.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7403521/0863.raze.bug.zip)
.

**Comment by SerialKicked** [comment]
Yep, that's kind of the problem it's not repeatable and stupid rare. I can't find it either and it has been floating around for years now. I keep reading and re-reading the code and I don't see where there could be a null exception. One day i'll catch it, but in the meantime, the game just skipping the job works well enough.

Be honest, without that warning you wouldn't have noticed it :D

**Comment by SerialKicked** [comment]
OMG it finally triggered at home while i was looking at it. Apparently a weird problem with the positioning of the "smoke" animation. Fixed.
