### ISSUE TITLE
locating hidden facility

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#59]
double click doesn't work and there is no other way to easily find it on the map (or anything else :-p )

![image](https://user-images.githubusercontent.com/91120787/138981271-4082bb74-bed1-40bc-a6a5-d729f82d71e0.png)

**Comment by IvanBajlo** [comment]
found it but there should really be easier way to navigate the map ;-)

![image](https://user-images.githubusercontent.com/91120787/138981516-02816a15-99e4-42f5-a136-de0cda91101b.png)

**Comment by SerialKicked** [comment]
Yes, i know, the "location locator" thing. Will do, will do :)
