### ISSUE TITLE
health visible when picking expedition

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#60]
otherwise one can take wrong team into battle ;-)

![image](https://user-images.githubusercontent.com/91120787/138982907-3e801f80-193e-454f-bb1f-156bf5df9eac.png)

**Comment by SerialKicked** [comment]
Agreed. (also and unrelated but this menu on screen, it should show weapon information for each guy)

**Comment by SerialKicked** [comment]
Done
