### ISSUE TITLE
butcher hotkey :p

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#62]
after large battles there could be a lot of bodies to butcher and way to select all of them and mark then for butchering would be nice ;-)

![image](https://user-images.githubusercontent.com/91120787/138997079-ccded032-0fc5-4dae-bf55-62796b8e88cf.png)

**Comment by SerialKicked** [comment]
Agreed

**Comment by SerialKicked** [comment]
done
