### ISSUE TITLE
when loading save carried corps gets dumped

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#63]
it seems that after loading save, game recalculates settlers jobs and corps they were carrying can get dumped which is kind annoying since now someone else has to go and pick it up again... can you add IF carrying corps THEN continue carrying it ;-)

**Comment by SerialKicked** [comment]
Savegames don't keep job information and never will to give them a chance to self-correct errors. 

The "i'm holding the corpse" thing is just a graphical trick run by the job, not actual data being saved. I can't really change any of that without making very large changes to the save system (and to "movebody" job types which i really really don't want to touch anymore, they work on prayer and goodwill)
