### ISSUE TITLE
butchering table not a factory

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#64]
making this setup way less useful

![image](https://user-images.githubusercontent.com/91120787/139045328-44c16970-600c-458f-963a-16af47fbe533.png)

**Comment by IvanBajlo** [comment]
also it seems closest butchering table isn't always selected... despite me building 6 right next to pasture 2 out of 3 pigs ended up on level above!?

![image](https://user-images.githubusercontent.com/91120787/139062368-32b72978-6991-4542-b7ef-281d251dba62.png)

![image](https://user-images.githubusercontent.com/91120787/139062430-cf98071c-7b68-4878-bce5-3d4ce76d4506.png)

**Comment by SerialKicked** [comment]
1) oh right, i promised to do that. I'll see what i can do.

2) The settler doesn't decide which one to pick, its the factory who are running the code (like factories) and all station share the the same list of butcherable things. It's probably not going to change. I'll see if I can add a "disable" checkbox on them, so you can at least disable one you don't need immediately.

**Comment by IvanBajlo** [comment]
excess tables are for post battle "cleanup" ;-)

**Comment by SerialKicked** [comment]
oki done
