### ISSUE TITLE
prisoner trader for mutants makes little sense?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#66]
1. very expensive meat ;-)

2. I'm guessing there is nothing preventing player from recruiting them which just causes headaches (plus possible bugs) unless they are cannibals

![image](https://user-images.githubusercontent.com/91120787/139059350-8fdbdd3a-80ba-4e04-83b3-2902192e8559.png)

**Comment by IvanBajlo** [comment]
yep... managed to recruit a human and if I attempt to click it on the name doesn't work only for mutants

![image](https://user-images.githubusercontent.com/91120787/139064924-f77da86c-6c7f-4eae-b81b-dd3c444bcb45.png)

**Comment by SerialKicked** [comment]
Slave traders are here for a good reason :p

(also it's not that expensive as you are literally swimming in money in this scenario given that all the expensive items are worthless to you and can be sold for profit).
