### ISSUE TITLE
Neo Roma and The Horde factions made peace?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#67]
and yes relations with in game Neo Roma are still at -100... either the event triggers for that other Neo Roma or it attempts to make peace but don't have effect?

![image](https://user-images.githubusercontent.com/91120787/139067101-00cec128-1511-4d02-9f32-3b16b5b15f1b.png)

**Comment by SerialKicked** [comment]
Oh right, leadership change.. Yeah it's still triggering, but to no effect. I'll add a check
