### ISSUE TITLE
prisoner riots, becomes new faction ignoring doors?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#69]
wtf?

![image](https://user-images.githubusercontent.com/91120787/139090368-7e8525d4-7e38-432d-8630-ce4fb37562b2.png)

**Comment by SerialKicked** [comment]
Uh he should be hostile faction, not civilian (which is why he's ignoring doors, civilians are a friendly faction). Not sure what's up.

**Comment by IvanBajlo** [comment]
second prisoner (on the ground level) also riots day or two later with the same results

[087 hayden.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7427490/087.hayden.zip)

**Comment by SerialKicked** [comment]
Yeah, after verification prisoners revert back to their previous faction when rioting. Bought prisoners are civilian.

**Comment by SerialKicked** [comment]
should be fixed
