### ISSUE TITLE
Slave raids for cannibals and others

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#7]
For cannibal player instead of searching for survivors found settlers would be basically cattle used for labor or meat. ;-)

Could be used instead of attack option for outposts or faction bases (maybe even human hostiles?)? Slave raid has X chance of bringing back prisoners depending on the expedition prison guard skill (can we have it change name to slave guard if slaver faction?)

Also if ever implemented slaver faction would only have access to slave raids since its members would look at any survivor as potential slave.

**Comment by SerialKicked** [comment]
Implemented via bomb collar expedition equipment
