### ISSUE TITLE
Scaling not working correctly during faction selection

### ISSUE THREAD

**Issue by StefanOssendorf** [AnarkisGaming/ATC-Feedback#70]
Hi, I'm in the midst of creating my first game and have an issue with selecting a faction icon in the selection screen.
![grafik](https://user-images.githubusercontent.com/5385401/140657359-4c62f3e8-6cf7-400a-8e71-587a08f873fd.png)
Event hough I try to click the icon where my mouse is the icon two to the right is being selected.

**Comment by StefanOssendorf** [comment]
Some notes after using the dialog a bit more:
It seems like the game _thinks_ the first icon of the second row is in fact in the first row and selectes the second item of the second row instead. So for me it looks like the code thinks the icon is rendered in the first row but actually in the second.
When I click to the right side of the last icon in the first row I select the first item of the second row.
I hope this makes sense to you 😅

**Comment by SerialKicked** [comment]
Thanks for reporting it.

I'll have a look, it shouldn't be too difficult to get that fixed. 

edit: Oki, i managed to reproduce when  scaling the UI to a different level than default settings. I'm not entirely sure why it happens in this sub menu and this submenu only, yet.

**Comment by SerialKicked** [comment]
Problem identified and fixed. It will be included in this week's patch. Thanks again for reporting it.

**Comment by StefanOssendorf** [comment]
You're welcome :-) and thanks for the quick fix :-D
