### ISSUE TITLE
Game crashes when UI sizes is changed during the tutorial

### ISSUE THREAD

**Issue by DarthB** [AnarkisGaming/ATC-Feedback#72]
I get stuck at the camp fire, when the tutorial wants me to add a job. 

The widget is too high, i.e. I cannot see the bottom part of the add job widget. I assume there must be the add job button. I headed to settings to change the UI scale. Afterwards the game crashes with a NULL Pointer Exception

**Comment by SerialKicked** [comment]
Is part of the UI off screen ? If so:
https://steamcommunity.com/app/727570/discussions/0/3052860266933736593/

Could you also drag & drop that null expection here?

**Comment by SerialKicked** [comment]
no null exception report, no fix.
