### ISSUE TITLE
factory constantly being destroyed?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#74]
Happy buggy New Year! ;)

![image](https://user-images.githubusercontent.com/91120787/147867233-75759981-53db-4e6d-952c-a94d6eb2675a.png)
![image](https://user-images.githubusercontent.com/91120787/147867236-693a5f7f-24f3-4c80-9270-b8494f2fe1f4.png)

**Comment by SerialKicked** [comment]
Fixed
