### ISSUE TITLE
expedition getting stuck when almost at target location

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#76]
I thought this was fixed some time ago... but it seems to still be happening and I can't find it listed so here it goes again...

if event triggers just when expedition is about to reach location it gets stuck in traveling forever, even loading save doesn't help, one has to manually move expedition and then move them back...

saved game
[090 traveling.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7803917/090.traveling.zip)

![image](https://user-images.githubusercontent.com/91120787/147977232-89836987-09ae-4b77-8c4d-d0f08db048fb.png)

**Comment by SerialKicked** [comment]
Uh indeed, I thought I fixed that... Welp, i'll have another look. thx.
