### ISSUE TITLE
map icons don't change status

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#77]
after getting attacked by fauna they don't change status to hostile/occupied or undefended

![image](https://user-images.githubusercontent.com/91120787/147978403-a123d3ac-80c1-4018-91c2-59af54d0056a.png)

![image](https://user-images.githubusercontent.com/91120787/147978470-f4755c37-1f33-46d1-8a20-54184961f40a.png)

**Comment by SerialKicked** [comment]
The menu itself probably doesn't refresh fully / in real time. until closed/reopened. 

I'll have a look.

**Comment by IvanBajlo** [comment]
there seems to be bug with outpost ownership in general... they seem to be reverting to previous owner!?

[090 outpost.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7810914/090.outpost.zip)

![image](https://user-images.githubusercontent.com/91120787/148135218-87e49daa-9254-40c0-9f92-3781f22346d2.png)

**Comment by SerialKicked** [comment]
There was a problem with savegames not storing/loading the proper faction information. It should be fixed.
