### ISSUE TITLE
vehicle gets hurt instead of expedition members? ;)

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#78]
it seems that during exploration instead of humans vehicle gets damaged 

![image](https://user-images.githubusercontent.com/91120787/147983568-cf0e7d90-041b-4058-b973-80210ae10c5b.png)

**Comment by SerialKicked** [comment]
This event can't touch the car itself, damage is just normal travel damage. 

I'll check why people are not hurt, tho.

**Comment by SerialKicked** [comment]
Nope, it's intended effect. Vehicle take periodic small damage during travel (on top of events), or not so small when going over dangerous terrain.

It's a feature, not a bug 😋
