### ISSUE TITLE
spiders shooting web has no tooltip and inflicts lot of damage quickly in 360 arc?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#79]
1. there is no tooltip like for pincer and carapace

2. spider web besides slowing their victims also inflicts lot of damage (like 30?) and because of rapid fire can be lethal

3. there seems to be no limitations and spiders will shoot automatically in any direction making it very difficult to ambush

![image](https://user-images.githubusercontent.com/91120787/147992472-baaaba81-43c2-45c2-a58f-13ba68e01b4c.png)

**Comment by SerialKicked** [comment]
1) npc turret slot ain't showing tooltip, game has no tooltips for turrets, as it's a weapon platform not a weapon proper, i'll see what i can do.

2) that's a lot of damage, if accurate, i'll fix that.

3) it's intended.
