### ISSUE TITLE
option to not repair traps when enemy is close?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#81]
to add to my previous post... a way to prevent your settlers from automatically repairing traps in the middle of the combat? maybe don't repair traps when in combat mode? (same should apply to collecting corpses and loot... pure heresy for any RPG player :D )

![image](https://user-images.githubusercontent.com/91120787/148002773-8dd112fb-78de-453a-b323-9a75d80708e4.png)

**Comment by SerialKicked** [comment]
They already don't do any of that?
