### ISSUE TITLE
infected building cannot be cleared?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#82]
it always has at lest 1 shambler after battle and is constantly spawning more?

![image](https://user-images.githubusercontent.com/91120787/148096084-70670911-fa7a-485e-96ce-fd5945fd4127.png)

**Comment by SerialKicked** [comment]
I'll get that fixed before weekend

**Comment by SerialKicked** [comment]
Killed like 30 bases, doesn't happen?

**Comment by IvanBajlo** [comment]
> Killed like 30 bases, doesn't happen?

I'll see if I can repeat it with new patch
