### ISSUE TITLE
 animals can be assigned to takeover buildings

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#83]
I'm mean it does makes sense to send them to the farm ;-)

![image](https://user-images.githubusercontent.com/91120787/148115908-619357f7-8eea-433d-8503-e51ebc81a6b4.png)

**Comment by SerialKicked** [comment]
Ooops, thanks

**Comment by IvanBajlo** [comment]
did some more testing... animals don't get assigned by they do make a mess of the menu

**Comment by SerialKicked** [comment]
agreed will fix.

**Comment by IvanBajlo** [comment]
I did managed to takeover with cow and sheep :D
