### ISSUE TITLE
visible strength of enemy expeditions

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#85]
at the moment mercs seem useless... I spent tons of money and had strength of 12 000 but mutant horde expedition 10 strong wiped them out with ease... only for themselves to be wiped out by shamblers!??? 

and defeating shamblers looks like mission impossible, I mean I like though fights but if this is how its going to be we are going to need much more firepower, like improvised tanks and APC which we can use in manual combat ;-)

![image](https://user-images.githubusercontent.com/91120787/148124041-e5a1c70a-eb0b-49a0-8318-499ff3160ed2.png)

**Comment by SerialKicked** [comment]
Problem is, a faction will always send a favorable fight for them if they have the manpower. So yeah, if they send an expedition, it's likely to win unless you reinforce while they are in transit. This probably left their main base relatively undefended, and wipeable by zombies. 

I'm tuning down the zombies, tho.

**Comment by SerialKicked** [comment]
Fixed: Infested buildings spawning enemies every 2 hours instead of every 2 days (lol oops)
