### ISSUE TITLE
famos-g1 is missing repair recipe

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#86]
one can only recycle damaged ones

also no pipe weapons can be recycled or I'm missing something?

![image](https://user-images.githubusercontent.com/91120787/148129795-0c22edc4-331c-4552-a678-053d5f2462f9.png)

**Comment by SerialKicked** [comment]
Thanks. Fixing. And, nope i did not add the data for pipe weapons to be disassembled. Might do.
