### ISSUE TITLE
picking up everything of the tile?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#87]
despite having plenty of carry space picking up items seems to be connected to individual item (or group of items depending on how they are dropped?) instead of tile total content so it can take multiple trips to clear a single tile?

![image](https://user-images.githubusercontent.com/91120787/148142788-012a3a36-5366-410d-b681-cd11b73aea5a.png)

**Comment by SerialKicked** [comment]
It's probably a side effect of  #90 
With that job not working, Game is relying on settlers doing it on their own, by "opportunistically" getting the times, and periodically clearing their inventory. 

With #90 being fixed, this one should be fixed too.
