### ISSUE TITLE
weird pathfinding?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#88]
for some reason instead of going directly between two pasture animals (when relocating) prefer to go via stairs to level above and then down

is this maybe a trick to speed up calculations since game stalls for few seconds (I'm guessing sewers are horrible for pathfinding) each time I move my spider horde to new pasture but that is fine ;-)

[090 pathfinding.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7811396/090.pathfinding.zip)

![image](https://user-images.githubusercontent.com/91120787/148145398-02dea1a1-6ba2-4449-81bb-8876cf423848.png)

**Comment by SerialKicked** [comment]
1) Yeah, sewers are absolute cancer to the pathfinding. 

2) Looking at the save (the bottle bug thing), it seems that going above ground is about 1-2 tiles shorter than going underground. At this level of error, the algorithm could have picked any. There's no "pathing cost" associated with using stairs. I could add one, like i do to force people not to walk all over farms unless forced to, but I don't think it's necessary.
