### ISSUE TITLE
fire spreads between animals!?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#89]
I had bunch of dogs in pasture spreading fire from one to other!??

and settler in combat mod just standing there doing nothing until catching fire and dying...

this might be a little bit overkill... I doubt any living being would just stand still next to someone burning until they caught fire and die and for fire to kill would need something to burn, so sheep would probably lot of material to burn butt dogs and pigs not so much and would probably survive at lest until burns get infected... 

also those fireballs do lot of damage to walls despite them being made from concrete... 

![image](https://user-images.githubusercontent.com/91120787/148460199-94135c7c-a538-4e7f-95b6-2b9b3ea59472.png)

**Comment by SerialKicked** [comment]
I'll check the wall thing. 

Fire spreading through animals is "normal", either a tile can burn or it can't. Calculations are kept to a minimum to keep FPS up with large fires. Checking who or what is providing fuel is not really an option.
