### ISSUE TITLE
items from expedition never picked up?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#90]
for some reason water bottles which expedition brought back ages ago never gets picked up and stored?

[090 bottle.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7825311/090.bottle.zip)

![image](https://user-images.githubusercontent.com/91120787/148467126-33801193-0922-4591-bd65-5b7c8078d2d2.png)

**Comment by IvanBajlo** [comment]
hmm it finally did happen even if it took ages... maybe reloading had something to do with it

**Comment by SerialKicked** [comment]
Seems like there's a problem in the storetile job when there's either too much to store, or one item ain't storable (like dirty water) but the other is. nice find. 

What likely happened after loading the save is that someone with a different job (or on break) grabbed the content of the tile by opportunity while doing something else.
