### ISSUE TITLE
laws buffs not applied to all new settlers?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#95]
I though this was fixed long time ago?

if check the dates it seems that in each new group only one settlers got laws applied while other nothing... if I revoke and again pass the laws then everyone gets all the buffs

also mood value should be listed under misc category in Menu: Population to make problems easier to spot

[090 laws.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7826012/090.laws.zip)

**Comment by SerialKicked** [comment]
Grumbl, stupid typo. yeah, happens when you press recruit "all". Fixed.
