### ISSUE TITLE
location status not properly saved?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#98]
it seems to me that after loading saved games certain location resets, this is most obvious in case with faction bases, spider or scorpion queen would destroys faction base but after loading game faction would be back in its control but no defense and I cannot attack it?

[0901 base.zip](https://github.com/AnarkisGaming/ATC-Feedback/files/7867746/0901.base.zip)

![image](https://user-images.githubusercontent.com/91120787/149449731-9bb261e6-738b-4027-adff-4438298769b9.png)

![image](https://user-images.githubusercontent.com/91120787/149449783-b15c29e2-39a3-4713-ba1d-69a6f74217bb.png)

**Comment by SerialKicked** [comment]
Oh shit, yeah i know what's up. I'll have to prevent the AI hordes from attacking AI faction HQs
