### ISSUE TITLE
can't move tables in bunkers?

### ISSUE THREAD

**Issue by IvanBajlo** [AnarkisGaming/ATC-Feedback#99]
in progenerated bunker I can move chairs but not tables?  

same applies to potted plants but they have zero use (currently)

![image](https://user-images.githubusercontent.com/91120787/150559711-8f2b0c97-8555-4e79-838e-01d6127e072d.png)

also there are two types of wooden shelves, one is standard decoration which player can build (and also move) but second one is named as storage (but can't be used as such) and also can't be moved?

![image](https://user-images.githubusercontent.com/91120787/150560404-7fedd7a0-595b-429b-9c5e-ba9b94a5773a.png)

**Comment by SerialKicked** [comment]
Most (if not all) furniture have a version you can build (with all the bells and whistles) and a "fake" version used by the map generator. This version is lacking their components (lighting, decoration, whatever) to save some ram and save size. 

It's likely that the bunker is still using the "fake" variants of some of those furniture in some of the rooms. This is basically the same "problem" with the non functioning lamps from #14 

I'll give it a look :)
